In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("data/2019.csv")
df.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Score                         156 non-null    float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy life expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Perceptions of corruption     156 non-null    float64
dtypes: float64(7), int64(1), object(1)
memory usage: 11.1+ KB

In [5]:
print(f"columns: {df.shape[1]}\nrows: {df.shape[0]}")

columns: 9
rows: 156

In [6]:
df.describe().round()

,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
count,156.0,156.0,156.0,156.0,156.0,156.0,156.0,156.0
mean,78.0,5.0,1.0,1.0,1.0,0.0,0.0,0.0
std,45.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
min,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,40.0,5.0,1.0,1.0,1.0,0.0,0.0,0.0
50%,78.0,5.0,1.0,1.0,1.0,0.0,0.0,0.0
75%,117.0,6.0,1.0,1.0,1.0,1.0,0.0,0.0
max,156.0,8.0,2.0,2.0,1.0,1.0,1.0,0.0

In [14]:
for col in df:
    per = df[col].isnull().sum() / df.shape[0] * 100
    print(f'{col}:     {per}')

Overall rank:     0.0
Country or region:     0.0
Score:     0.0
GDP per capita:     0.0
Social support:     0.0
Healthy life expectancy:     0.0
Freedom to make life choices:     0.0
Generosity:     0.0
Perceptions of corruption:     0.0

In [18]:
df.columns = df.columns.str.lower()

## Findings from 2019 EDA