# World Happiness Index Prediction

## Load Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import seaborn as sns

## Data Extraction

In [3]:
path = "C:/Users/ASUS/Desktop/git pro/world happiness report/data"
dataset_list = os.listdir(path)
print(dataset_list)

['2015.csv', '2016.csv', '2017.csv', '2018.csv', '2019.csv']

In [4]:
datasets = [pd.read_csv(path + "/" + dataset) for dataset in dataset_list]
df_2015, df_2016, df_2017, df_2018, df_2019 = datasets

##  Initial EDA

In [5]:
df_2015.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [6]:
df_2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Region                         158 non-null    object
 2   Happiness Rank                 158 non-null    int64
 3   Happiness Score                158 non-null    float64
 4   Standard Error                 158 non-null    float64
 5   Economy (GDP per Capita)       158 non-null    float64
 6   Family                         158 non-null    float64
 7   Health (Life Expectancy)       158 non-null    float64
 8   Freedom                        158 non-null    float64
 9   Trust (Government Corruption)  158 non-null    float64
 10  Generosity                     158 non-null    float64
 11  Dystopia Residual              158 non-null    float64
dtypes: float64(9), int64(1), object(2)
memory usage: 14.9+ KB

In [7]:
print(f"columns: {df_2015.shape[1]}\nrows: {df_2015.shape[0]}")

columns: 12
rows: 158

In [8]:
df_2015.describe().round()

,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
count,158.0,158.0,158.0,158.0,158.0,158.0,158.0,158.0,158.0,158.0
mean,79.0,5.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,2.0
std,46.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
min,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,40.0,5.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0
50%,80.0,5.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,2.0
75%,119.0,6.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,2.0
max,158.0,8.0,0.0,2.0,1.0,1.0,1.0,1.0,1.0,4.0

In [9]:
print(df_2015.columns.tolist())
print("--" * 50)
print(df_2016.columns.tolist())
print("--" * 50)
print(df_2017.columns.tolist())
print("--" * 50)
print(df_2018.columns.tolist())
print("--" * 50)
print(df_2019.columns.tolist())

['Country', 'Region', 'Happiness Rank', 'Happiness Score', 'Standard Error', 'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity', 'Dystopia Residual']
----------------------------------------------------------------------------------------------------
['Country', 'Region', 'Happiness Rank', 'Happiness Score', 'Lower Confidence Interval', 'Upper Confidence Interval', 'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity', 'Dystopia Residual']
----------------------------------------------------------------------------------------------------
['Country', 'Happiness.Rank', 'Happiness.Score', 'Whisker.high', 'Whisker.low', 'Economy..GDP.per.Capita.', 'Family', 'Health..Life.Expectancy.', 'Freedom', 'Generosity', 'Trust..Government.Corruption.', 'Dystopia.Residual']
----------------------------------------------------------------------------------------------------
['Overall rank', 'Country or region', 'Score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']
----------------------------------------------------------------------------------------------------
['Overall rank', 'Country or region', 'Score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

In [10]:
df_2015.drop(columns=["Region"], inplace= True)

In [11]:
# sns.pairplot(df_2015, hue="RegionId")

In [12]:
df_2015_null = df_2015.isnull().sum()
df_2015_null_per = (df_2015_null / len(df_2015)) * 100

print(f"---null values---\n\n{'Feaure':<20} {'number of null values':>20} {'percentage':>20}")

for feature , n , perc in zip(df_2015_null.index, df_2015_null.values, df_2015_null_per.values):
    print(f'{feature:<20} {n:>20} {perc:>20}')

---null values---

Feaure               number of null values           percentage
Country                                 0                  0.0
Happiness Rank                          0                  0.0
Happiness Score                         0                  0.0
Standard Error                          0                  0.0
Economy (GDP per Capita)                    0                  0.0
Family                                  0                  0.0
Health (Life Expectancy)                    0                  0.0
Freedom                                 0                  0.0
Trust (Government Corruption)                    0                  0.0
Generosity                              0                  0.0
Dystopia Residual                       0                  0.0

## PreProcessing

## Scaling and Normalizing

## Feature Engineering

## Model Selection

## Test & Evaluate